### ISSUE TITLE
NoClassDefFoundError: Could not initialize class

### ISSUE THREAD

**Issue by PPatrick-star** [PPatrick-star/Study_wiki#4]
2022-04-29 00:17:24.012 [ERROR][                                ] io.undertow.request                                                     UT005023: Exception handling request to /admin/using/list
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class org.xnio.channels.Channels
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1055)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)

**Comment by PPatrick-star** [comment]
-  다음 오류도 발생
2022-04-29 00:20:26.256 [ERROR][                                ] io.undertow.request                                                     UT005023: Exception handling request to /admin/using/list
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.io.IOError: java.io.FileNotFoundException: Invalid file path
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1055)

**Comment by PPatrick-star** [comment]
- corretto-1.8.0_302 버전으로 수정한 후에 오류 발생안함
![image](https://user-images.githubusercontent.com/66957670/165803852-81c56ed8-8637-4db2-b3d3-9a40d20ca122.png)

![image](https://user-images.githubusercontent.com/66957670/165804107-dfa7d8ab-4c18-458c-b3ea-bcb9b4374b49.png)
